/**
 * DropForge's personalised installer. The owner, 2026-09-27: "can we somehow
 * automatically fill in their license key that is generated by their user?
 * its sort of an annoying step during the installation".
 *
 * A buyer's ticketed download is named "Install DropForge (K7Q2M9XD).exe".
 * The installer reads the token from its own file name, and the app trades it
 * once (POST /v1/downloads/install-token) for the account's activation code,
 * then activates with that code as if it had been typed. A token is good for
 * seven days and one trade. After that, or without one, the app asks for the
 * code or a sign-in as before.
 *
 * The token is derived from the download ticket, so every request for the
 * same download, a resumed one included, names the file the same way. Only a
 * keyed hash of it is stored.
 */

import { createHmac, randomUUID } from "node:crypto";
import { db } from "../config/db.js";
import { env } from "../config/env.js";

export const INSTALL_TOKENS_TABLE = "download_install_tokens";
export const INSTALL_TOKEN_TTL_MS = 7 * 24 * 60 * 60 * 1000;
// The activation codes' alphabet: no O/0, no I/1, no U.
export const INSTALL_TOKEN_ALPHABET = "ABCDEFGHJKLMNPQRSTVWXYZ23456789";
export const INSTALL_TOKEN_LENGTH = 8;
const TOKEN_SHAPE = new RegExp(`^[${INSTALL_TOKEN_ALPHABET}]{${INSTALL_TOKEN_LENGTH}}$`);

function key(purpose) {
  if (!env.jwtSecret) throw new Error("JWT_SECRET is required for install tokens");
  return createHmac("sha256", env.jwtSecret).update(`sendforge-install-token/${purpose}/v1`).digest();
}

const keyedHash = (value, purpose) => createHmac("sha256", key(purpose)).update(value).digest("hex");

// Unbiased: a byte picks a symbol only below the largest multiple of 31.
function deriveToken(ticket, attempt) {
  const limit = 256 - (256 % INSTALL_TOKEN_ALPHABET.length);
  let out = "";
  for (let round = 0; out.length < INSTALL_TOKEN_LENGTH; round += 1) {
    const bytes = createHmac("sha256", key("derive")).update(`${attempt}:${round}:${ticket}`).digest();
    for (const byte of bytes) {
      if (byte >= limit) continue;
      out += INSTALL_TOKEN_ALPHABET[byte % INSTALL_TOKEN_ALPHABET.length];
      if (out.length === INSTALL_TOKEN_LENGTH) break;
    }
  }
  return out;
}

/** The token as a person or a file name gives it, or "" if it cannot be one. */
export function normalizeInstallToken(value) {
  const token = String(value || "").trim().toUpperCase().replace(/[\s-]/g, "");
  return TOKEN_SHAPE.test(token) ? token : "";
}

/** Creates the table the first time it is needed, as migrations are not run on deploy. */
let tableReady = null;
export function ensureInstallTokensTable(trx = db) {
  if (trx !== db) return createInstallTokensTable(trx);
  tableReady ||= createInstallTokensTable(db).catch((error) => {
    tableReady = null;
    throw error;
  });
  return tableReady;
}

export async function createInstallTokensTable(knex) {
  if (await knex.schema.hasTable(INSTALL_TOKENS_TABLE)) return;
  await knex.schema.createTable(INSTALL_TOKENS_TABLE, (t) => {
    t.uuid("id").primary();
    t.uuid("user_id").notNullable();
    t.text("product_slug").notNullable();
    t.text("token_hash").notNullable().unique();
    t.text("ticket_hash").notNullable();
    t.timestamp("expires_at", { useTz: true }).notNullable();
    t.timestamp("used_at", { useTz: true });
    t.timestamp("created_at", { useTz: true }).notNullable().defaultTo(knex.fn.now());
    t.index(["user_id", "product_slug"]);
  });
}

/**
 * The token that names this download's installer: the same for every request
 * with the same ticket. Null only after four collisions with other downloads
 * in a row, when the file keeps its plain name.
 */
export async function installTokenForTicket({ userId, slug, ticket, now = Date.now(), trx = db }) {
  await ensureInstallTokensTable(trx);
  const ticketHash = keyedHash(String(ticket), "ticket");
  for (let attempt = 0; attempt < 4; attempt += 1) {
    const token = deriveToken(String(ticket), attempt);
    const tokenHash = keyedHash(token, "token");
    const inserted = await trx(INSTALL_TOKENS_TABLE)
      .insert({
        id: randomUUID(),
        user_id: String(userId),
        product_slug: slug,
        token_hash: tokenHash,
        ticket_hash: ticketHash,
        expires_at: new Date(now + INSTALL_TOKEN_TTL_MS),
      })
      .onConflict("token_hash")
      .ignore()
      .returning("id");
    if (inserted.length) return token;
    const held = await trx(INSTALL_TOKENS_TABLE).where({ token_hash: tokenHash }).first("ticket_hash");
    if (held?.ticket_hash === ticketHash) return token; // the same download, asked again
  }
  return null;
}

/**
 * Trades a token, once, for its account's activation code. A token that is
 * unknown, used or expired is refused the same way. `activationCodeFor` is
 * deviceActivation.service.js's getOrCreateActivationCode.
 */
export async function redeemInstallToken(value, { hasEntitlement, activationCodeFor, now = Date.now(), trx = db }) {
  const token = normalizeInstallToken(value);
  if (!token) return { error: "invalid_input" };
  await ensureInstallTokensTable(trx);
  const row = await trx(INSTALL_TOKENS_TABLE)
    .where({ token_hash: keyedHash(token, "token") })
    .whereNull("used_at")
    .where("expires_at", ">", new Date(now))
    .first();
  if (!row) return { error: "unknown_install_token" };
  // A refunded purchase activates nothing, token or not.
  if (!(await hasEntitlement(row.user_id, row.product_slug))) {
    return { error: "entitlement_required", productSlug: row.product_slug };
  }
  const code = await activationCodeFor(row.user_id, row.product_slug);
  const spent = await trx(INSTALL_TOKENS_TABLE)
    .where({ id: row.id })
    .whereNull("used_at")
    .update({ used_at: new Date(now) });
  if (!spent) return { error: "unknown_install_token" };
  return { productSlug: row.product_slug, activationCode: code.code };
}
