// DropForge's personalised installer. The owner, 2026-09-27: "can we somehow
// automatically fill in their license key that is generated by their user?
// its sort of an annoying step during the installation".
//
// Runs the real downloads route and the real token service against an
// in-process Postgres (PGlite); only GitHub is a stand-in.

import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import http from "node:http";
import test, { after, before } from "node:test";
import express from "express";

process.env.JWT_SECRET ||= "install-tokens-test-secret-at-least-32-bytes-long";

const { db } = await import("../src/config/db.js");
const { attachPglite } = await import("./helpers/pglite-db.js");
const { grantProductEntitlement, revokeProductEntitlement, hasProductEntitlement } = await import(
  "../src/services/entitlement.service.js"
);
const { getOrCreateActivationCode } = await import("../src/services/deviceActivation.service.js");
const { createDownloadsRouter, issueDownloadTicket } = await import("../src/routes/downloads.routes.js");
const {
  INSTALL_TOKENS_TABLE,
  INSTALL_TOKEN_TTL_MS,
  installTokenForTicket,
  normalizeInstallToken,
  redeemInstallToken,
} = await import("../src/services/installTokens.service.js");
const { up: devicesUp } = await import("../src/db/migrations/20260921_create_device_activations.js");

const FILE = Buffer.from("MZ" + "drop".repeat(500));
const TOKEN_IN_NAME = /^attachment; filename="Install DropForge \(([ABCDEFGHJKLMNPQRSTVWXYZ2-9]{8})\)\.exe"/;
let server;
let base;

before(async () => {
  await attachPglite(db);
  await devicesUp(db);
  const router = createDownloadsRouter({
    auth: (req, res, next) => {
      const user = /^Bearer (\S+)$/.exec(req.headers.authorization || "")?.[1];
      if (!user) return res.status(401).json({ error: "missing_token" });
      req.user = { sub: user };
      return next();
    },
    fetchAsset: async () => new Response(FILE, { status: 200, headers: { "content-length": String(FILE.length) } }),
    siteUrl: "https://sendforge.test",
  });
  const app = express();
  app.use(express.json());
  app.use("/v1/downloads", router);
  server = http.createServer(app);
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  base = `http://127.0.0.1:${server.address().port}`;
});

after(async () => {
  await new Promise((resolve) => server.close(resolve));
  await db.destroy();
});

async function buyer() {
  const id = randomUUID();
  await db("users").insert({ id, email: `${id}@example.com` });
  await grantProductEntitlement({ userId: id, productSlug: "forgedrop", source: "test" });
  return id;
}

async function download(ticket, headers = {}) {
  const res = await fetch(`${base}/v1/downloads/forgedrop?ticket=${encodeURIComponent(ticket)}`, { headers });
  await res.arrayBuffer();
  return TOKEN_IN_NAME.exec(res.headers.get("content-disposition") || "")?.[1] || null;
}

function trade(token) {
  return fetch(`${base}/v1/downloads/install-token`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ token }),
  });
}

test("a buyer's copy is named with a token: the same one for the same download, a new one for the next", async () => {
  const owner = await buyer();
  const first = issueDownloadTicket({ userId: owner, slug: "forgedrop" }).ticket;
  const token = await download(first);
  assert.ok(token, "the file name carries a token");
  assert.equal(await download(first), token, "asked again, the same name");
  assert.equal(await download(first, { Range: "bytes=10-" }), token, "a resumed download keeps its name");
  const second = issueDownloadTicket({ userId: owner, slug: "forgedrop", now: Date.now() + 1000 }).ticket;
  const next = await download(second);
  assert.ok(next);
  assert.notEqual(next, token);

  const rows = await db(INSTALL_TOKENS_TABLE).where({ user_id: owner });
  assert.equal(rows.length, 2);
  for (const row of rows) {
    assert.equal(row.product_slug, "forgedrop");
    assert.ok(![token, next].some((plain) => row.token_hash.includes(plain) || row.ticket_hash.includes(plain)), "only keyed hashes are kept");
    const days = (new Date(row.expires_at) - new Date(row.created_at)) / (24 * 60 * 60 * 1000);
    assert.ok(days > 6.99 && days < 7.01, "good for seven days");
  }
});

test("the token trades once for its account's activation code", async () => {
  const owner = await buyer();
  const token = await download(issueDownloadTicket({ userId: owner, slug: "forgedrop" }).ticket);
  const code = (await getOrCreateActivationCode(owner, "forgedrop")).code;

  // As the installer's name gives it, or as a person types it.
  const res = await trade(`${token.slice(0, 4).toLowerCase()}-${token.slice(4)}`);
  assert.equal(res.status, 200);
  assert.deepEqual(await res.json(), { ok: true, productSlug: "forgedrop", activationCode: code });
  const again = await trade(token);
  assert.equal(again.status, 404);
  assert.deepEqual(await again.json(), { error: "unknown_install_token" });

  // Another buyer's token is theirs alone.
  const other = await buyer();
  const theirs = await download(issueDownloadTicket({ userId: other, slug: "forgedrop" }).ticket);
  const traded = await (await trade(theirs)).json();
  assert.equal(traded.activationCode, (await getOrCreateActivationCode(other, "forgedrop")).code);
  assert.notEqual(traded.activationCode, code);
});

test("an expired token, a made-up one and a refunded purchase trade for nothing", async () => {
  const owner = await buyer();
  const deps = { hasEntitlement: hasProductEntitlement, activationCodeFor: getOrCreateActivationCode };
  const start = Date.now();
  const old = await installTokenForTicket({ userId: owner, slug: "forgedrop", ticket: "an-old-ticket", now: start });
  assert.deepEqual(await redeemInstallToken(old, { ...deps, now: start + INSTALL_TOKEN_TTL_MS + 1000 }), { error: "unknown_install_token" });

  assert.equal((await trade("ZZZZZZZZ")).status, 404);
  assert.deepEqual(await (await trade("not a token")).json(), { error: "invalid_input" });

  const token = await installTokenForTicket({ userId: owner, slug: "forgedrop", ticket: "a-refunded-ticket" });
  await revokeProductEntitlement(owner, "forgedrop");
  const refused = await trade(token);
  assert.equal(refused.status, 403);
  assert.deepEqual(await refused.json(), { error: "entitlement_required", productSlug: "forgedrop" });
  // Refused is not spent: bought again, the same installer works.
  await grantProductEntitlement({ userId: owner, productSlug: "forgedrop", source: "test" });
  assert.equal((await trade(token)).status, 200);
});

test("a token is only a shape a person can type back", () => {
  assert.equal(normalizeInstallToken(" k7q2-m9xd "), "K7Q2M9XD");
  assert.equal(normalizeInstallToken("K7Q2M9X0"), "", "no zero");
  assert.equal(normalizeInstallToken("K7Q2M9XU"), "", "no U");
  assert.equal(normalizeInstallToken("K7Q2M9X"), "", "eight characters");
  assert.equal(normalizeInstallToken(null), "");
});
